
platform :ios, '8.0'

inhibit_all_warnings!

target 'iReader' do
    
    pod 'Objective-LevelDB', '2.1.5'
    pod 'SVProgressHUD', '2.1.2'
    pod 'Masonry', '1.1.0'
    pod 'ZipArchive', '~> 1.4.0'
    pod 'FLEX', '~> 2.0', :configurations => ['Debug']

end

