# cocoapods update
# sudo gem install cocoapods -version

platform :ios, '10.0'

inhibit_all_warnings!

workspace 'iRead.xcworkspace'


# debug_pods
def debug_pods
  pod 'FLEX', '~> 4.1.1', :configurations => ['Debug']
  pod 'EpubBooks', :git => 'https://github.com/zhiyongzou/EpubBooks.git', :branch => 'main', :configurations => ['Debug']
end

# common_pods
def common_pods
  pod 'IRHexColor', '~> 0.0.2'
  pod 'AEXML', '~> 4.5.0'
  pod 'SSZipArchive', '~> 2.2.2'
  pod 'FMDB', '~> 2.7.5'
end

# local_pods
# " ./ " 表示当前文件所在目录下
# " ../ " 表示当前文件所在目录下的上一级目录
def local_pods
  pod 'DTCoreText', :path => './DTCoreText'
  pod 'DTFoundation', :path => './DTFoundation'
end

# common_pods
common_pods

# ==================================== Targets ==================================== #

target 'iRead' do

  # debug pods
  debug_pods
  local_pods
  
  # for iRead
  pod 'SnapKit', '~> 5.0.1'
  pod 'CMPopTipView', '~> 2.3.2'
  pod 'HGCircularSlider', '~> 2.2.0'

end

target 'IRCommonLib' do
  project 'IRCommonLib/IRCommonLib.xcodeproj'

end

# https://github.com/CocoaPods/CocoaPods/issues/8069
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 10.0
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
            end
        end
    end
end
